-- ===========================================================================
-- SEC-08 (c) — backup / migration tables left in the live schema
-- ===========================================================================
-- ⛔ NOT APPLIED. Requires explicit owner approval per CLAUDE.md §3.
--
-- This file originally held sections (a), (b) and (c). **Sections (a) and (b)
-- were approved and applied on 2026-07-30**, and are recorded as:
--
--   supabase/migrations/20260730_sec08b_revoke_truncate_grants.sql
--     TRUNCATE / TRIGGER / REFERENCES revoked from anon + authenticated on
--     every table in public. 210 grants removed (70 per privilege class).
--     TRUNCATE is not subject to RLS, so this was the largest item in the file.
--
--   supabase/migrations/20260730_sec08a_rpc_grant_hygiene.sql
--     anon EXECUTE revoked on 12 privileged RPCs. Supabase's
--     `anon_security_definer_function_executable` advisor finding went from
--     2 WARN to none.
--
-- Each of those files carries the dependency review that was completed before
-- it was applied, and the measured before/after state. Only section (c) below
-- remains, and it was deliberately left out of that approval rather than
-- silently bundled in.
--
-- One question this file asked has since been answered:
--   Q: does the deployed consume_credits() carry its dual-authorization guard?
--      (the repo file being present does not prove it was applied)
--   A: ✅ VERIFIED 2026-07-30 — pg_get_functiondef(...) LIKE
--      '%forbidden_user_mismatch%' returns true. The guard is live, so
--      consume_credits needs no change beyond the anon revoke already applied.
--
-- ── (c) Backup table left in the live schema ───────────────────────────────
-- weakness_signals_bak_mig_b1_20260702 (476 rows) is a pre-migration snapshot
-- still exposed through the API with RLS enabled but NO policies. It returns
-- nothing to clients today, which is the correct outcome by accident rather
-- than by design: add one permissive policy later and it starts serving data.
--
-- MEASURED 2026-07-30: has_table_privilege('authenticated', …, 'SELECT') is
-- already false for both tables below, because RLS-with-no-policy blocks the
-- read regardless of the grant. So this section is **defence in depth against a
-- future policy being added**, not a fix for a live exposure — which is why it
-- was not urgent enough to bundle into the security approval above.
--
-- The stronger alternative, if these tables are genuinely finished with: move
-- them out of the API's reach entirely (`ALTER TABLE … SET SCHEMA private`) or
-- drop them. Revoking grants leaves them discoverable in the public schema.
-- Worth deciding which, rather than applying the weaker form by default.
REVOKE ALL ON public.weakness_signals_bak_mig_b1_20260702 FROM anon, authenticated;
REVOKE ALL ON public.mig_b1_map                            FROM anon, authenticated;

-- ===========================================================================
-- Post-apply verification
--   SELECT grantee, privilege_type FROM information_schema.role_table_grants
--    WHERE table_schema='public'
--      AND table_name IN ('weakness_signals_bak_mig_b1_20260702','mig_b1_map')
--      AND grantee IN ('anon','authenticated');
--   -- expect: no rows
-- ===========================================================================
