#!/usr/bin/env node
// fetch-fonts.mjs — self-host the brand fonts for the design-system bundle.
//
//   node .design-sync/fetch-fonts.mjs
//
// The live site loads Manrope, DM Sans and JetBrains Mono from the Google Fonts
// CDN via <link>, and the repo holds no font files. The claude.ai/design bundle
// needs them locally so rendered designs use the real brand faces instead of
// system fallbacks. This downloads them once into ds-bundle/fonts/ and writes a
// fonts.css whose @font-face rules point at the local copies.
//
// build-tokens.mjs runs this automatically when ds-bundle/fonts/ is missing, so
// a fresh clone reproduces the full bundle with one command. Run it directly to
// refresh the files.
//
// NETWORK REQUIRED. Offline, the bundle still builds and still validates — the
// validator treats a missing font as a warning, not an error — but it would ship
// with system fonts. Check the file count before uploading.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = join(new URL('..', import.meta.url).pathname.replace(/\/$/, ''), 'ds-bundle/fonts');
mkdirSync(OUT, { recursive: true });

// A browser UA is required — Google Fonts serves woff2 only to clients it
// believes support it, and older-looking clients get ttf.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Weight union across all 46 pages, collected from their <link> hrefs.
const FAMILIES = [
  ['Manrope', '400;500;600;700;800;900'],
  ['DM Sans', '300;400;500;600;700'],
  ['JetBrains Mono', '400;500;600;700'],
];

// latin + latin-ext only. The site ships no Arabic webface, so Arabic already
// falls back to system fonts in production; shipping an Arabic subset here would
// make the design tool render something the real site cannot.
const KEEP = new Set(['latin', 'latin-ext']);

let css = `/* Si Math AI brand fonts — self-hosted for offline/CSP-safe rendering.
 * Generated by .design-sync/fetch-fonts.mjs. Source: Google Fonts (the live
 * site loads these from the CDN via <link>).
 * Subsets: latin, latin-ext only — the site ships no Arabic webface, so Arabic
 * text falls back to system fonts here exactly as it does in production.
 */

`;

let files = 0, bytes = 0;
for (const [family, weights] of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%20/g, '+')}`
    + `:wght@${weights}&display=swap`;
  const sheet = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
  // Google emits one /* subset */ comment before each @font-face block.
  for (const block of sheet.split(/(?=\/\*\s*[a-z0-9-]+\s*\*\/)/).filter((b) => b.includes('@font-face'))) {
    const subset = /\/\*\s*([a-z0-9-]+)\s*\*\//.exec(block)?.[1];
    if (!KEEP.has(subset)) continue;
    const src = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block);
    if (!src) continue;
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
    const name = `${family.replace(/\s+/g, '')}-${weight}-${style}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(src[1], { headers: { 'User-Agent': UA } })).arrayBuffer());
    writeFileSync(join(OUT, name), buf);
    files++; bytes += buf.length;
    css += block.replace(/\/\*[^*]*\*\/\s*/, '').replace(src[1], name).trim() + '\n\n';
  }
}

writeFileSync(join(OUT, 'fonts.css'), css);
console.error(`✓ ${files} woff2 files, ${(bytes / 1024).toFixed(0)} KB → ${OUT}`);
if (!files) { console.error('✗ no fonts downloaded — check network access to fonts.googleapis.com'); process.exitCode = 1; }
