#!/usr/bin/env bash
# scripts/pin-cdn-sri.sh
#
# SEC-07 — pin every third-party CDN asset to an exact version and verify its
# Subresource Integrity hash.
#
# The pins in the HTML were generated by this script and are already applied.
# Run it to (a) re-verify that the committed hashes still match the real
# packages, or (b) move a pin to a new version.
#
#   ./scripts/pin-cdn-sri.sh --check   # verify committed hashes; CI gate
#   ./scripts/pin-cdn-sri.sh           # recompute and print the current values
#
# WHY IT READS FROM THE NPM REGISTRY, NOT FROM JSDELIVR
# -----------------------------------------------------
# jsdelivr is a pass-through CDN: for a path inside a package it serves the
# bytes from the npm tarball unmodified. So the tarball is the authoritative
# source for the hash, and using it has two advantages over fetching the CDN
# URL directly:
#
#   1. The tarball download can be checked against npm's own published
#      `dist.integrity` (a SHA-512 the registry signs off on) BEFORE anything
#      is hashed. Fetching the CDN gives you no independent value to check
#      against — you would be trusting the very channel you are trying to pin.
#   2. registry.npmjs.org is reachable from restricted build environments that
#      block general CDN egress.
#
# The KaTeX hashes this produces match the values published in KaTeX's own
# documentation, which is an independent confirmation that the method is right.
#
# ⚠️ DO NOT pin a `*.min.js` path that does not exist in the tarball.
# `@supabase/supabase-js` ships `dist/umd/supabase.js` and NO `supabase.min.js`.
# Requesting the `.min.js` path makes jsdelivr minify on the fly, and that
# output is generated per-request by jsdelivr's own minifier — it is not in any
# package, it has no authoritative hash, and it can change when they upgrade
# their toolchain. Four pages used that path before this fix; they now use the
# real file. The package's `jsdelivr` field (`dist/umd/supabase.js`) is what a
# bare `@supabase/supabase-js@<ver>` URL resolves to, so both forms converge on
# the same hashable file.
#
set -euo pipefail

PIN_SUPABASE_JS="${PIN_SUPABASE_JS:-2.110.8}"
PIN_KATEX="${PIN_KATEX:-0.16.11}"

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

for tool in curl openssl python3 tar; do
  command -v "$tool" >/dev/null || { echo "FAIL: $tool not found" >&2; exit 1; }
done

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Download a package tarball and verify it against npm's published integrity.
# Refuses to continue if the registry's own hash does not match.
fetch_pkg() {
  local pkg="$1" ver="$2" out="$3"
  local meta="$WORK/meta.json"
  curl -sSfL --max-time 90 "https://registry.npmjs.org/${pkg}" -o "$meta"

  local tarball expected
  tarball=$(python3 -c "import json;print(json.load(open('$meta'))['versions']['$ver']['dist']['tarball'])")
  expected=$(python3 -c "import json;print(json.load(open('$meta'))['versions']['$ver']['dist'].get('integrity',''))")

  curl -sSfL --max-time 90 "$tarball" -o "$out"

  if [ -n "$expected" ]; then
    local actual="sha512-$(openssl dgst -sha512 -binary "$out" | openssl base64 -A)"
    if [ "$actual" != "$expected" ]; then
      echo "FAIL: tarball integrity mismatch for ${pkg}@${ver}" >&2
      echo "      registry: $expected" >&2
      echo "      computed: $actual" >&2
      exit 1
    fi
    echo "  ${pkg}@${ver}: tarball verified against registry integrity"
  else
    echo "  WARN: registry published no integrity for ${pkg}@${ver}" >&2
  fi
}

# SHA-384, base64 — the SRI format — for one path inside a tarball.
sri_of() {
  local tgz="$1" path="$2"
  tar xzf "$tgz" -C "$WORK" "package/${path}" 2>/dev/null || {
    echo "FAIL: ${path} is not in the tarball. If it is a .min.* path, the CDN" >&2
    echo "      is generating it on the fly and it CANNOT be pinned. Use the" >&2
    echo "      real file that ships in the package instead." >&2
    exit 1
  }
  printf 'sha384-%s' "$(openssl dgst -sha384 -binary "$WORK/package/${path}" | openssl base64 -A)"
}

echo "Verifying packages…"
fetch_pkg "@supabase/supabase-js" "$PIN_SUPABASE_JS" "$WORK/supa.tgz"
fetch_pkg "katex"                 "$PIN_KATEX"       "$WORK/katex.tgz"

SUPA_SRI="$(sri_of "$WORK/supa.tgz"  'dist/umd/supabase.js')"
KJS_SRI="$( sri_of "$WORK/katex.tgz" 'dist/katex.min.js')"
KAR_SRI="$( sri_of "$WORK/katex.tgz" 'dist/contrib/auto-render.min.js')"
KCSS_SRI="$(sri_of "$WORK/katex.tgz" 'dist/katex.min.css')"

echo
echo "Computed SRI hashes:"
echo "  supabase-js@${PIN_SUPABASE_JS} dist/umd/supabase.js  ${SUPA_SRI}"
echo "  katex@${PIN_KATEX} katex.min.js                      ${KJS_SRI}"
echo "  katex@${PIN_KATEX} auto-render.min.js                ${KAR_SRI}"
echo "  katex@${PIN_KATEX} katex.min.css                     ${KCSS_SRI}"
echo

fail=0
note() { echo "  $1"; }

# Every committed hash must be one we just recomputed, and nothing may be left
# unpinned or floating.
for f in ./*.html; do
  [ -e "$f" ] || continue

  while IFS= read -r line; do
    [ -z "$line" ] && continue
    case "$line" in
      *"$SUPA_SRI"*|*"$KJS_SRI"*|*"$KAR_SRI"*|*"$KCSS_SRI"*) ;;
      *) note "STALE HASH  $f: $(printf '%s' "$line" | cut -c1-60)…"; fail=1 ;;
    esac
  done < <(grep -o 'integrity="sha384-[^"]*"' "$f" 2>/dev/null || true)

  if grep -q 'cdn\.jsdelivr\.net' "$f" 2>/dev/null; then
    while IFS= read -r tag; do
      case "$tag" in
        *integrity=*) ;;
        *) note "NO SRI      $f: $(printf '%s' "$tag" | cut -c1-80)…"; fail=1 ;;
      esac
    done < <(grep -oE '<(script|link)[^>]*(src|href)="https://cdn\.jsdelivr\.net[^"]*"[^>]*>' "$f" || true)
  fi

  if grep -qE 'supabase-js@[0-9]+["/]|supabase-js/\+esm' "$f" 2>/dev/null; then
    if grep -qE '<(script|link)[^>]*supabase-js@[0-9]+["/]|<script[^>]*supabase-js/\+esm' "$f" 2>/dev/null; then
      note "FLOATING    $f: unpinned supabase-js range in a live tag"; fail=1
    fi
  fi
done

if [ "$fail" -ne 0 ]; then
  echo
  echo "pin-cdn-sri: FAILED — CDN pins are stale, missing, or floating."
  [ "$CHECK_ONLY" -eq 1 ] && exit 1
  echo "Re-run without --check and apply the hashes printed above."
  exit 1
fi

echo "pin-cdn-sri: PASS — every CDN asset is version-pinned and hash-verified."
